name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sonar_version: [5.0.2.4997, 6.1.0.4477, 7.2.0.5079]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup sonar-scanner for each matrix version
      - name: Setup SonarQube
        uses: ./
        with:
          version: ${{ matrix.sonar_version }}

      - name: Check sonar-scanner version
        run: sonar-scanner --version